#!/usr/bin/env python
import os, sys

class Program(object):
	def __init__(self):
		for x in range(len(sys.argv)):
			if sys.argv[x] == '-':
				sys.argv[x] = '/dev/stdin'

		if len(sys.argv) == 1:
			sys.stderr.write('usage: %s FILE1 [FILE2]\n' % sys.argv[0])
			sys.exit(1)
		elif len(sys.argv) == 2:
			file1 = sys.stdin
			file2 = open(sys.argv[1])
		elif len(sys.argv) == 3:
			file1 = open(sys.argv[1])
			file2 = open(sys.argv[2])

		words1 = set(x.strip() for x in file1.readlines())
		words2 = set(x.strip() for x in file2.readlines())
		prog = os.path.basename(sys.argv[0])
		print('\n'.join(getattr(self, prog)(words1, words2)))
	
	def intersect(self, a, b):
		return [x for x in a if x in b]

	def complement(self, a, b):
		return [x for x in a if x not in b]

	def rcomplement(self, a, b):
		return [x for x in b if x not in a]

	def union(self, a, b):
		return a.union(b)

if __name__ == '__main__':
	Program()
